### ISSUE TITLE
Can you add show size back?thanks

### ISSUE THREAD

**Issue by michaelzs1994** [danieljbingham/google-image-sizer#1]

**Comment by danieljbingham** [comment]
Maybe my mind has gone blank, but what is Show Size? Do you mean the Exact Size filter?

**Comment by christopheranderton** [comment]
I thinks he means the label on the bottom at the images in the search results (with the image dimension like: 3200x2400 etc).

**Comment by michaelzs1994** [comment]
> 我认为他是指搜索结果中图片底部的标签（图片尺寸为：3200x2400等）。

yep

**Comment by danieljbingham** [comment]
Thanks! This feature is available in the latest update of the extension
